### ISSUE TITLE
1.0.8 causes breaking change 

### ISSUE THREAD

**Issue by DamienBitrise** [DroidsOnRoids/bitrise-step-sonarqube-scanner#23]
Can you change this new version to a major version release please so Bitrise users can opt into the change?

See: https://github.com/bitrise-io/bitrise-steplib/pull/3184#issuecomment-910914420

eg. 2.0.0 since it is a breaking change

**Comment by koral--** [comment]
I think that change itself is not breaking but there is a bug appearing on mac os stacks (probably only in certain configurations).
Actual issue is tracked here: https://github.com/DroidsOnRoids/bitrise-step-sonarqube-scanner/issues/22

**Comment by koral--** [comment]
Fixed in 1.0.9
