### ISSUE TITLE
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0 + Andriod Issue

### ISSUE THREAD

**Issue by SatishDevOps-azure** [DroidsOnRoids/bitrise-step-sonarqube-scanner#25]
Hi ,

I am facing the below for android application , sonar plugin has downgraded to 1.0.7 ,1.0.6 ,1.0.5 and 1.0.9 but no luck . can you please help to address the issue.
Thanks!

![Capture](https://user-images.githubusercontent.com/50496922/131955400-a8d33642-99e9-4d4c-b33d-c416f932117a.JPG)

**Comment by efremovartem792** [comment]
We are facing exactly the same problem. It stopped working a few days ago

**Comment by koral--** [comment]
Does it reproduce when you enable debug option?

**Comment by efremovartem792** [comment]
@koral-- which debug option do you mean?

**Comment by koral--** [comment]
`is_debug` step input.

**Comment by SatishDevOps-azure** [comment]
Thanks Koral updated step version (1.0.9) is available in bitrise ,Now it is good :)
