### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by frozenchocolate** [DroidsOnRoids/bitrise-step-sonarqube-scanner#29]
Sorry but I am new to Bitrise and when I tried to integrate your step, I got the error `SonarQube server [http://localhost:9000/] can not be reached`. Now I probably missed something, your guide says "Local server can be spawned in previous script step" but I don't know exactly how to do that, can you please help me out?

**Comment by koral--** [comment]
You can check the official docs: https://docs.sonarqube.org/latest/setup-and-upgrade/install-the-server/
Here is how it was done a few years ago in tests of this plugin: https://github.com/DroidsOnRoids/bitrise-step-sonarqube-scanner/blob/c976ca19f9471605901aeefd2197a97120c7c9b4/bitrise.yml#L68

**Comment by frozenchocolate** [comment]
@koral-- Thank you!
