### ISSUE TITLE
Use both sonar-project.properties and scanner-properties provided by Bitrise

### ISSUE THREAD

**Issue by Hugal31** [DroidsOnRoids/bitrise-step-sonarqube-scanner#3]
I think I would be nice to be able to use both `sonar-project.properties` and the scanner-properties provided by Bitrise.

I want to be able to use Bitrise properties, for example the Sonarqube server URL and login, but also let the project properties near the project itself, in `sonar-scanner.properties`.

This could be done by appending `scanner-properties` to the `sonar-scanner.properties` file, for example `echo -n "${scanner_properties}" >> sonar-project.properties`.

**Comment by koral--** [comment]
LGTM, I'll try to add it ASAP.
