### ISSUE TITLE
Can we use the step with SonarCloud not SonarQube

### ISSUE THREAD

**Issue by aviv-moataznabil** [DroidsOnRoids/bitrise-step-sonarqube-scanner#32]
Hi, can we use the step with SonarCloud not SonarQube?

**Comment by koral--** [comment]
IIRC it should be possible. Just specify appropriate properties, like host set to `sonarcloud.io` etc.

**Comment by aviv-moataznabil** [comment]
@koral-- I tried it and I git this error

<img width="1193" alt="Screenshot 2023-10-27 at 16 35 08" src="https://github.com/DroidsOnRoids/bitrise-step-sonarqube-scanner/assets/143813523/1d0512bd-a0b8-4c3c-9a66-0eaad5165642">
<img width="1036" alt="Screenshot 2023-10-27 at 16 35 31" src="https://github.com/DroidsOnRoids/bitrise-step-sonarqube-scanner/assets/143813523/39324924-a07a-41c3-8123-d5ebc51cf4f7">
