### ISSUE TITLE
Not Authorized warning sometimes, though creds have been confirmed correct

### ISSUE THREAD

**Issue by jimResdiary** [DroidsOnRoids/bitrise-step-sonarqube-scanner#33]
Hi, we've been experiencing issues with the SQ bitrise step scan on our iOS and Android builds with intermittent error message:

`ERROR: Not authorized. Analyzing this project requires authentication. Please provide a user token in sonar.login or other credentials in sonar.login and sonar.password.`

Sometimes it has completed with success, though others with this failure. The large majority of scans are failing in this way now.

We have checked the credentials and even updated them with new ones to make sure. We are not aware of any call limits either and on these occasions when it fails nothing has been changed that we are aware of compared to the succeeded scans.

After opening a ticket with Bitrise support they advised I reach out directly here, any guidance here appreciated
Thanks

**Comment by koral--** [comment]
That error message is not printed by this step but by the sonar scanner CLI.
I can suggest you using the latest version (5.0.1.3006 at the time of writing), you can set it via `scanner_version` input.
If it does not help, reach out to the https://community.sonarsource.com/

**Comment by jimResdiary** [comment]
Thanks Koral, will do!
